### ISSUE TITLE
Check your master password and try again

### ISSUE THREAD

**Issue by kvbik** [dmaasland/lastpass-authenticator-export#10]
I am super sure about the username, password and OTP - testing the very same credentials in a browser works - still I am getting::

```
Login failed!
<response><error message="Check your master password and try again." cause="password_invalid" email="my@email.com" is_passwordless_login=""  /></response>
```

PS: I've even tried grabbing the session id and csrf from the browser, but there may be something else broken. Since I was getting *Padding is incorrect.*....

**Comment by alvarhansen** [comment]
In case it helps someone. For me the issue was that my `Password Iterations` setting was not the default `100100`.

This can be changed by:
1. Open `Account Settings` in your browser (`Open My Vault` → `Account Settings`)
2. Press `Show Advanced Settings`
3. Set `General` → `Security` → `Password Iterations` to exactly `100100`

[(Reference)](https://github.com/lastpass/lastpass-cli/issues/604#issue-894502620)

After that, running the script was successful.
