### ISSUE TITLE
Error after supplying credentials

### ISSUE THREAD

**Issue by fhirrepo** [dmaasland/lastpass-authenticator-export#9]
Login failed!
 
/*error message="Account settings are preventing you from logging in with this device. Look for an email from LastPass or go to your account settings to enable." cause="mobilerestricted" allowmultifactortrust="true" tempuid="xxxxx" trustexpired="0" trustlabel="" hidedisable="false" enabled_providers="" enabled_provider_names="" email="xxxxxx" login_method="mfa_login"  */

did not get any email
disabled MFA
should the mode of lastpass be set as computer or mobile for it to work? just have 1 switch left.
any idea based on above?

**Comment by dmaasland** [comment]
I've finally had the chance to look at this. Turns out there was a missing parameter that prevented the email from being sent. I've added that in the latest [commit](https://github.com/dmaasland/lastpass-authenticator-export/commit/154422b60152f328435e71bed722be5788808486).

Please do a git pull and try again :)

**Comment by fhirrepo** [comment]
it worked! i can finally be done with lastpass. thank you !!!!
